// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Demo: typeof import('./components/demo/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
  }
}

export { }
